[workspace]

members = [
      "binary-search",
      "quick-sort",
      "back-track-maze",
      "bin-tree",
      "tests",
]
          
[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
#panic = "abort"
