name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Target
      run: rustup target install x86_64-unknown-linux-gnu
    - uses: actions/checkout@v1
    - name: Lint
      run: cargo fmt -- --check
    - name: Build 
      run: cargo build --release 
    - name: Test
      run: cargo test --release
